// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdministratorRole is the golang structure for table administrator_role.
type AdministratorRole struct {
	Id              uint        `json:"id"               ` //
	AdministratorId uint        `json:"administrator_id" ` // 管理员id
	RoleId          uint        `json:"role_id"          ` // 角色id
	CreatedAt       *gtime.Time `json:"created_at"       ` // 创建时间
	UpdatedAt       *gtime.Time `json:"updated_at"       ` // 更新时间
}
