// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Administrator is the golang structure for table administrator.
type Administrator struct {
	Id            uint        `json:"id"              ` //
	Username      string      `json:"username"        ` // 用户名
	Password      string      `json:"password"        ` // MD5密码
	Nickname      string      `json:"nickname"        ` // 昵称
	Avatar        string      `json:"avatar"          ` // 头像地址
	Status        string      `json:"status"          ` // 状态 normal 正常 disabled 禁用
	Remark        string      `json:"remark"          ` // 备注
	LastLoginIp   string      `json:"last_login_ip"   ` // 最后登陆IP
	LastLoginDate *gtime.Time `json:"last_login_date" ` // 最后登陆时间
	CreatedAt     *gtime.Time `json:"created_at"      ` // 注册时间
	UpdatedAt     *gtime.Time `json:"updated_at"      ` // 更新时间
}
