// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenu is the golang structure for table admin_menu.
type AdminMenu struct {
	Id                 uint        `json:"id"                   ` //
	Name               string      `json:"name"                 ` // 菜单名称
	Path               string      `json:"path"                 ` // 前端路由地址，可以是外链
	ParentId           uint        `json:"parent_id"            ` // 父id
	Identification     string      `json:"identification"       ` // 后端权限标识符
	Method             string      `json:"method"               ` // 请求方法
	FrontComponentPath string      `json:"front_component_path" ` // 前端组件路径
	Icon               string      `json:"icon"                 ` // 菜单图标
	Sort               int         `json:"sort"                 ` // 显示顺序，越小越靠前
	Status             string      `json:"status"               ` // 状态 normal 正常 disabled 禁用
	CreatedAt          *gtime.Time `json:"created_at"           ` // 创建时间
	UpdatedAt          *gtime.Time `json:"updated_at"           ` // 更新时间
	Type               string      `json:"type"                 ` // 菜单类型
	LinkType           string      `json:"link_type"            ` //
}
