// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Ptype string `json:"ptype" ` //
	V0    string `json:"v_0"   ` //
	V1    string `json:"v_1"   ` //
	V2    string `json:"v_2"   ` //
	V3    string `json:"v_3"   ` //
	V4    string `json:"v_4"   ` //
	V5    string `json:"v_5"   ` //
}
