// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Config is the golang structure for table config.
type Config struct {
	Id        uint        `json:"id"         ` //
	Module    string      `json:"module"     ` // 所属模块
	Key       string      `json:"key"        ` // 键值
	Value     string      `json:"value"      ` // 值
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updated_at" ` // 更新时间
}
