// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EmailRecords is the golang structure for table _email_records.
type EmailRecords struct {
	Id        uint        `json:"id"         ` //
	UserId    uint        `json:"user_id"    ` // 用户id
	Username  string      `json:"username"   ` // 用户名
	Type      string      `json:"type"       ` // 类型
	Email     string      `json:"email"      ` // 邮箱
	Title     string      `json:"title"      ` // 标题
	Content   string      `json:"content"    ` // 内容
	Error     string      `json:"error"      ` // 错误信息
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	UpdateAt  *gtime.Time `json:"update_at"  ` // 更新时间
}
