// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FollowOrShieldUserRelation is the golang structure for table _follow_or_shield_user_relation.
type FollowOrShieldUserRelation struct {
	Id             uint        `json:"id"              ` //
	UserId         uint        `json:"user_id"         ` // 用户id
	Username       string      `json:"username"        ` // 用户名
	TargetUserId   uint        `json:"target_user_id"  ` // 被关注｜屏蔽用户id
	TargetUsername string      `json:"target_username" ` // 被关注｜屏蔽用户名
	Type           string      `json:"type"            ` // 类型 关注: follow,屏蔽: shield
	CreatedAt      *gtime.Time `json:"created_at"      ` // 创建时间
}
