// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Messages is the golang structure for table _messages.
type Messages struct {
	Id              uint        `json:"id"               ` //
	UserId          uint        `json:"user_id"          ` // 用户id
	Username        string      `json:"username"         ` // 用户名
	RepliedUserId   uint        `json:"replied_user_id"  ` // 被回复用户id,用户a向用户b回复，用户b为 被回复用户id
	RepliedUsername string      `json:"replied_username" ` // 被回复用户名
	PostId          uint        `json:"post_id"          ` // 关联主题id
	ReplyId         uint        `json:"reply_id"         ` // 关联回复id
	Type            string      `json:"type"             ` // 消息类型
	IsRead          int         `json:"is_read"          ` // 是否已读，否: 0,是: 1
	CreatedAt       *gtime.Time `json:"created_at"       ` // 创建时间
	DeletedAt       *gtime.Time `json:"deleted_at"       ` // 删除时间
}
