// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeCategories is the golang structure for table _node_categories.
type NodeCategories struct {
	Id                uint        `json:"id"                  ` //
	Name              string      `json:"name"                ` // 分类名称
	ParentId          uint        `json:"parent_id"           ` // 父节点id
	IsIndexNavigation int         `json:"is_index_navigation" ` // 是否首页导航显示
	Sort              int         `json:"sort"                ` // 显示顺序越小越靠前
	CreatedAt         *gtime.Time `json:"created_at"          ` // 创建时间
	DeletedAt         *gtime.Time `json:"deleted_at"          ` // 删除时间
}
