// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
	Id             uint        `json:"id"             ` //
	Name           string      `json:"name"           ` // 角色名
	Identification string      `json:"identification" ` // 角色标识符
	Sort           int         `json:"sort"           ` // 显示顺序，越小越靠前
	Status         string      `json:"status"         ` // 状态 normal 正常 disabled 禁用
	CreatedAt      *gtime.Time `json:"created_at"     ` // 创建时间
	UpdatedAt      *gtime.Time `json:"updated_at"     ` // 更新时间
}
