// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SensitiveWords is the golang structure for table _sensitive_words.
type SensitiveWords struct {
	Id        uint        `json:"id"         ` //
	Type      string      `json:"type"       ` // 类型
	Word      string      `json:"word"       ` // 敏感词
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	UpdateAt  *gtime.Time `json:"update_at"  ` // 更新时间
}
