// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ThanksOrShieldOrCollectContentRelation is the golang structure for table _thanks_or_shield_or_collect_content_relation.
type ThanksOrShieldOrCollectContentRelation struct {
	Id             uint        `json:"id"              ` //
	UserId         uint        `json:"user_id"         ` // 用户id
	Username       string      `json:"username"        ` // 用户名
	TargetId       uint        `json:"target_id"       ` // 被感谢｜屏蔽|收藏 主题id|回复id
	AdditionalId   uint        `json:"additional_id"   ` // 附加id，当target_id为回复id时，additional_id为主题id
	TargetUserId   uint        `json:"target_user_id"  ` // 被感谢｜屏蔽|收藏 用户id
	TargetUsername string      `json:"target_username" ` // 被感谢用户名
	Type           string      `json:"type"            ` // 类型 感谢主题: thanks_posts,感谢回复: thanks_reply,屏蔽主题: shield_posts,屏蔽回复: shield_reply,收藏主题:collect_posts
	CreatedAt      *gtime.Time `json:"created_at"      ` // 创建时间
}
