// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPostsHistories is the golang structure for table _user_posts_histories.
type UserPostsHistories struct {
	Id        uint        `json:"id"         ` //
	UserId    uint        `json:"user_id"    ` // 用户id
	Username  string      `json:"username"   ` // 用户名
	PostsId   uint        `json:"posts_id"   ` // 关联主题id
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	DeletedAt *gtime.Time `json:"deleted_at" ` // 删除时间
}
