// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdministratorForDao is the golang structure of table ga_administrator for DAO operations like Where/data.
type Administrator struct {
	g.Meta        `orm:"dto:true"`
	Id            interface{} //
	Username      interface{} // 用户名
	Password      interface{} // MD5密码
	Nickname      interface{} // 昵称
	Avatar        interface{} // 头像地址
	Status        interface{} // 状态 normal 正常 disabled 禁用
	Remark        interface{} // 备注
	LastLoginIp   interface{} // 最后登陆IP
	LastLoginDate *gtime.Time // 最后登陆时间
	CreatedAt     *gtime.Time // 注册时间
	UpdatedAt     *gtime.Time // 更新时间
}
