// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CasbinRuleForDao is the golang structure of table ga_casbin_rule for DAO operations like Where/data.
type CasbinRule struct {
	g.Meta `orm:"dto:true"`
	Ptype  interface{} //
	V0     interface{} //
	V1     interface{} //
	V2     interface{} //
	V3     interface{} //
	V4     interface{} //
	V5     interface{} //
}
