// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigForDao is the golang structure of table ga_config for DAO operations like Where/data.
type Config struct {
	g.Meta    `orm:"dto:true"`
	Id        interface{} //
	Module    interface{} // 所属模块
	Key       interface{} // 键值
	Value     interface{} // 值
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
