// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EmailRecords is the golang structure of table forum_email_records for DAO operations like Where/data.
type EmailRecords struct {
	g.Meta    `orm:"table:forum_email_records, do:true"`
	Id        interface{} //
	UserId    interface{} // 用户id
	Username  interface{} // 用户名
	Type      interface{} // 类型
	Email     interface{} // 邮箱
	Title     interface{} // 标题
	Content   interface{} // 内容
	Error     interface{} // 错误信息
	CreatedAt *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
}
