// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Nodes is the golang structure of table forum_nodes for DAO operations like Where/data.
type Nodes struct {
	g.Meta         `orm:"table:forum_nodes, do:true"`
	Id             interface{} //
	Name           interface{} // 节点名称
	Keyword        interface{} // 节点关键词
	Description    interface{} // 节点描述
	Detail         interface{} // 节点详情
	Img            interface{} // 节点图片
	ParentId       interface{} // 父节点id
	IsIndex        interface{} // 是否首页显示
	IsDisabledEdit interface{} // 是否禁用编辑和删除,1是 0否
	Sort           interface{} // 显示顺序越小越靠前
	CreatedAt      *gtime.Time // 创建时间
	DeletedAt      *gtime.Time // 删除时间
	IsVirtual      interface{} //
	CategoryId     interface{} //
}
