// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeCategories is the golang structure of table forum_node_categories for DAO operations like Where/data.
type NodeCategories struct {
	g.Meta            `orm:"table:forum_node_categories, do:true"`
	Id                interface{} //
	Name              interface{} // 分类名称
	ParentId          interface{} // 父节点id
	IsIndexNavigation interface{} // 是否首页导航显示
	Sort              interface{} // 显示顺序越小越靠前
	CreatedAt         *gtime.Time // 创建时间
	DeletedAt         *gtime.Time // 删除时间
}
