// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Prompts is the golang structure of table forum_prompts for DAO operations like Where/data.
type Prompts struct {
	g.Meta      `orm:"table:forum_prompts, do:true"`
	Id          interface{} //
	Position    interface{} // 提示语位置
	Content     interface{} // 提示语内容
	Description interface{} // 简介
	IsDisabled  interface{} // 状态：0 正常 1禁用
	CreatedAt   *gtime.Time // 创建时间
	UpdateAt    *gtime.Time // 更新时间
}
