// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Replies is the golang structure of table forum_replies for DAO operations like Where/data.
type Replies struct {
	g.Meta          `orm:"table:forum_replies, do:true"`
	Id              interface{} //
	PostsId         interface{} // 主题id
	UserId          interface{} // 用户id
	Username        interface{} // 用户名
	RelationUserIds interface{} // 涉及用户ids，多个以逗号分隔
	Content         interface{} // 内容
	CharacterAmount interface{} // 字符长度
	ThanksAmount    interface{} // 感谢次数
	ShieldedAmount  interface{} // 被屏蔽次数
	Status          interface{} // 状态：no_audit, normal, shielded
	CreatedAt       *gtime.Time // 创建时间
	UpdatedAt       *gtime.Time // 更新时间
	DeletedAt       *gtime.Time // 删除时间
}
