// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoleMenuForDao is the golang structure of table ga_role_menu for DAO operations like Where/data.
type RoleMenu struct {
	g.Meta    `orm:"dto:true"`
	Id        interface{} //
	MenuId    interface{} // 管理员id
	RoleId    interface{} // 角色id
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
