// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SensitiveWords is the golang structure of table forum_sensitive_words for DAO operations like Where/data.
type SensitiveWords struct {
	g.Meta    `orm:"table:forum_sensitive_words, do:true"`
	Id        interface{} //
	Type      interface{} // 类型
	Word      interface{} // 敏感词
	CreatedAt *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
}
