// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPostsHistories is the golang structure of table forum_user_posts_histories for DAO operations like Where/data.
type UserPostsHistories struct {
	g.Meta    `orm:"table:forum_user_posts_histories, do:true"`
	Id        interface{} //
	UserId    interface{} // 用户id
	Username  interface{} // 用户名
	PostsId   interface{} // 关联主题id
	CreatedAt *gtime.Time // 创建时间
	DeletedAt *gtime.Time // 删除时间
}
