// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure of table forum_users for DAO operations like Where/data.
type Users struct {
	g.Meta              `orm:"table:forum_users, do:true"`
	Id                  interface{} //
	Username            interface{} // 用户名
	Email               interface{} // email
	Description         interface{} // 简介
	Password            interface{} // MD5密码
	Avatar              interface{} // 头像地址
	Status              interface{} // 二进制位,0111 由低到高分别代表 禁止登录，禁止发帖，禁止回复，尚未激活
	PostsAmount         interface{} // 创建主题次数
	ReplyAmount         interface{} // 回复次数
	ShieldedAmount      interface{} // 被屏蔽次数
	FollowByOtherAmount interface{} // 被关注次数
	TodayActivity       interface{} // 今日活跃度
	Balance             interface{} // 余额
	Site                interface{} // 个人站点
	Company             interface{} // 所在公司
	Job                 interface{} // 工作职位
	Location            interface{} // 所在地
	Signature           interface{} // 个人签名
	Introduction        interface{} // 个人简介
	Remark              interface{} // 备注
	LastLoginIp         interface{} // 最后登陆IP
	LastLoginTime       *gtime.Time // 最后登陆时间
	CreatedAt           *gtime.Time // 注册时间
	UpdatedAt           *gtime.Time // 更新时间
	DeletedAt           *gtime.Time // 删除时间
}
