// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// adminLogDao is the data access object for table ga_admin_log.
// You can define custom methods on it to extend its functionality as you wish.
type adminLogDao struct {
	*internal.AdminLogDao
}

var (
	// AdminLog is globally public accessible object for table ga_admin_log operations.

	AdminLog = adminLogDao{
		internal.NewAdminLogDao(),
	}
)

// Fill with you ideas below.
