// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// administratorRoleDao is the data access object for table ga_administrator_role.
// You can define custom methods on it to extend its functionality as you wish.
type administratorRoleDao struct {
	*internal.AdministratorRoleDao
}

var (
	// AdministratorRole is globally public accessible object for table ga_administrator_role operations.
	AdministratorRole = administratorRoleDao{
		internal.NewAdministratorRoleDao(),
	}
)

// Fill with you ideas below.
