// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// administratorDao is the data access object for table ga_administrator.
// You can define custom methods on it to extend its functionality as you wish.
type administratorDao struct {
	*internal.AdministratorDao
}

var (
	// Administrator is globally public accessible object for table ga_administrator operations.
	Administrator = administratorDao{
		internal.NewAdministratorDao(),
	}
)

// Fill with you ideas below.
