// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalBalanceChangeLogDao is internal type for wrapping internal DAO implements.
type internalBalanceChangeLogDao = *internal.BalanceChangeLogDao

// BalanceChangeLogDao is the data access object for table forum_balance_change_log.
// You can define custom methods on it to extend its functionality as you wish.
type BalanceChangeLogDao struct {
	internalBalanceChangeLogDao
}

var (
	// BalanceChangeLog is globally public accessible object for table forum_balance_change_log operations.
	BalanceChangeLog = BalanceChangeLogDao{
		internal.NewBalanceChangeLogDao(),
	}
)

// Fill with you ideas below.
