// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalEmailRecordsDao is internal type for wrapping internal DAO implements.
type internalEmailRecordsDao = *internal.EmailRecordsDao

// EmailRecordsDao is the data access object for table forum_email_records.
// You can define custom methods on it to extend its functionality as you wish.
type EmailRecordsDao struct {
	internalEmailRecordsDao
}

var (
	// EmailRecords is globally public accessible object for table forum_email_records operations.
	EmailRecords = EmailRecordsDao{
		internal.NewEmailRecordsDao(),
	}
)

// Fill with you ideas below.
