// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalNodeCategoriesDao is internal type for wrapping internal DAO implements.
type internalNodeCategoriesDao = *internal.NodeCategoriesDao

// NodeCategoriesDao is the data access object for table forum_node_categories.
// You can define custom methods on it to extend its functionality as you wish.
type NodeCategoriesDao struct {
	internalNodeCategoriesDao
}

var (
	// NodeCategories is globally public accessible object for table forum_node_categories operations.
	NodeCategories = NodeCategoriesDao{
		internal.NewNodeCategoriesDao(),
	}
)

// Fill with you ideas below.
