// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalPostsDao is internal type for wrapping internal DAO implements.
type internalPostsDao = *internal.PostsDao

// PostsDao is the data access object for table forum_posts.
// You can define custom methods on it to extend its functionality as you wish.
type PostsDao struct {
	internalPostsDao
}

var (
	// Posts is globally public accessible object for table forum_posts operations.
	Posts = PostsDao{
		internal.NewPostsDao(),
	}
)

// Fill with you ideas below.
