// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalRepliesDao is internal type for wrapping internal DAO implements.
type internalRepliesDao = *internal.RepliesDao

// RepliesDao is the data access object for table forum_replies.
// You can define custom methods on it to extend its functionality as you wish.
type RepliesDao struct {
	internalRepliesDao
}

var (
	// Replies is globally public accessible object for table forum_replies operations.
	Replies = RepliesDao{
		internal.NewRepliesDao(),
	}
)

// Fill with you ideas below.
