// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// roleMenuDao is the data access object for table ga_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type roleMenuDao struct {
	*internal.RoleMenuDao
}

var (
	// RoleMenu is globally public accessible object for table ga_role_menu operations.
	RoleMenu = roleMenuDao{
		internal.NewRoleMenuDao(),
	}
)

// Fill with you ideas below.
