// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalSensitiveWordsDao is internal type for wrapping internal DAO implements.
type internalSensitiveWordsDao = *internal.SensitiveWordsDao

// SensitiveWordsDao is the data access object for table forum_sensitive_words.
// You can define custom methods on it to extend its functionality as you wish.
type SensitiveWordsDao struct {
	internalSensitiveWordsDao
}

var (
	// SensitiveWords is globally public accessible object for table forum_sensitive_words operations.
	SensitiveWords = SensitiveWordsDao{
		internal.NewSensitiveWordsDao(),
	}
)

// Fill with you ideas below.
