// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalUserPostsHistoriesDao is internal type for wrapping internal DAO implements.
type internalUserPostsHistoriesDao = *internal.UserPostsHistoriesDao

// UserPostsHistoriesDao is the data access object for table forum_user_posts_histories.
// You can define custom methods on it to extend its functionality as you wish.
type UserPostsHistoriesDao struct {
	internalUserPostsHistoriesDao
}

var (
	// UserPostsHistories is globally public accessible object for table forum_user_posts_histories operations.
	UserPostsHistories = UserPostsHistoriesDao{
		internal.NewUserPostsHistoriesDao(),
	}
)

// Fill with you ideas below.
