// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalUsersDao is internal type for wrapping internal DAO implements.
type internalUsersDao = *internal.UsersDao

// UsersDao is the data access object for table forum_users.
// You can define custom methods on it to extend its functionality as you wish.
type UsersDao struct {
	internalUsersDao
}

var (
	// Users is globally public accessible object for table forum_users operations.
	Users = UsersDao{
		internal.NewUsersDao(),
	}
)

// Fill with you ideas below.
