// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminMenuDao is the data access object for table ga_admin_menu.
type AdminMenuDao struct {
	Table   string           // Table is the underlying table name of the DAO.
	Group   string           // Group is the database configuration group name of current DAO.
	Columns AdminMenuColumns // Columns contains all the column names of Table for convenient usage.
}

// AdminMenuColumns defines and stores column names for table ga_admin_menu.
type AdminMenuColumns struct {
	Id                 string //
	Name               string // 菜单名称
	Path               string // 前端路由地址，可以是外链
	ParentId           string // 父id
	Identification     string // 后端权限标识符
	Method             string // 请求方法
	FrontComponentPath string // 前端组件路径
	Icon               string // 菜单图标
	Sort               string // 显示顺序，越小越靠前
	Status             string // 状态 normal 正常 disabled 禁用
	CreatedAt          string // 创建时间
	UpdatedAt          string // 更新时间
	Type               string // 菜单类型
	LinkType           string //
}

//  adminMenuColumns holds the columns for table ga_admin_menu.
var adminMenuColumns = AdminMenuColumns{
	Id:                 "id",
	Name:               "name",
	Path:               "path",
	ParentId:           "parent_id",
	Identification:     "identification",
	Method:             "method",
	FrontComponentPath: "front_component_path",
	Icon:               "icon",
	Sort:               "sort",
	Status:             "status",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	Type:               "type",
	LinkType:           "link_type",
}

// NewAdminMenuDao creates and returns a new DAO object for table data access.
func NewAdminMenuDao() *AdminMenuDao {
	return &AdminMenuDao{
		Group:   "default",
		Table:   "ga_admin_menu",
		Columns: adminMenuColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminMenuDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminMenuDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminMenuDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
