// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RepliesDao is the data access object for table forum_replies.
type RepliesDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns RepliesColumns // columns contains all the column names of Table for convenient usage.
}

// RepliesColumns defines and stores column names for table forum_replies.
type RepliesColumns struct {
	Id              string //
	PostsId         string // 主题id
	UserId          string // 用户id
	Username        string // 用户名
	RelationUserIds string // 涉及用户ids，多个以逗号分隔
	Content         string // 内容
	CharacterAmount string // 字符长度
	ThanksAmount    string // 感谢次数
	ShieldedAmount  string // 被屏蔽次数
	Status          string // 状态：no_audit, normal, shielded
	CreatedAt       string // 创建时间
	UpdatedAt       string // 更新时间
	DeletedAt       string // 删除时间
}

//  RepliesColumns holds the columns for table forum_replies.
var repliesColumns = RepliesColumns{
	Id:              "id",
	PostsId:         "posts_id",
	UserId:          "user_id",
	Username:        "username",
	RelationUserIds: "relation_user_ids",
	Content:         "content",
	CharacterAmount: "character_amount",
	ThanksAmount:    "thanks_amount",
	ShieldedAmount:  "shielded_amount",
	Status:          "status",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

// NewRepliesDao creates and returns a new DAO object for table data access.
func NewRepliesDao() *RepliesDao {
	return &RepliesDao{
		group:   "default",
		table:   "forum_replies",
		columns: repliesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RepliesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RepliesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RepliesDao) Columns() RepliesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RepliesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RepliesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RepliesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
