// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RoleDao is the data access object for table ga_role.
type RoleDao struct {
	Table   string      // Table is the underlying table name of the DAO.
	Group   string      // Group is the database configuration group name of current DAO.
	Columns RoleColumns // Columns contains all the column names of Table for convenient usage.
}

// RoleColumns defines and stores column names for table ga_role.
type RoleColumns struct {
	Id             string //
	Name           string // 角色名
	Identification string // 角色标识符
	Sort           string // 显示顺序，越小越靠前
	Status         string // 状态 normal 正常 disabled 禁用
	CreatedAt      string // 创建时间
	UpdatedAt      string // 更新时间
}

//  roleColumns holds the columns for table ga_role.
var roleColumns = RoleColumns{
	Id:             "id",
	Name:           "name",
	Identification: "identification",
	Sort:           "sort",
	Status:         "status",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

// NewRoleDao creates and returns a new DAO object for table data access.
func NewRoleDao() *RoleDao {
	return &RoleDao{
		Group:   "default",
		Table:   "ga_role",
		Columns: roleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RoleDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
