// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SensitiveWordsDao is the data access object for table forum_sensitive_words.
type SensitiveWordsDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns SensitiveWordsColumns // columns contains all the column names of Table for convenient usage.
}

// SensitiveWordsColumns defines and stores column names for table forum_sensitive_words.
type SensitiveWordsColumns struct {
	Id        string //
	Type      string // 类型
	Word      string // 敏感词
	CreatedAt string // 创建时间
	UpdateAt  string // 更新时间
}

//  SensitiveWordsColumns holds the columns for table forum_sensitive_words.
var sensitiveWordsColumns = SensitiveWordsColumns{
	Id:        "id",
	Type:      "type",
	Word:      "word",
	CreatedAt: "created_at",
	UpdateAt:  "update_at",
}

// NewSensitiveWordsDao creates and returns a new DAO object for table data access.
func NewSensitiveWordsDao() *SensitiveWordsDao {
	return &SensitiveWordsDao{
		group:   "default",
		table:   "forum_sensitive_words",
		columns: sensitiveWordsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SensitiveWordsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SensitiveWordsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SensitiveWordsDao) Columns() SensitiveWordsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SensitiveWordsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SensitiveWordsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SensitiveWordsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
