// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserPostsHistoriesDao is the data access object for table forum_user_posts_histories.
type UserPostsHistoriesDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns UserPostsHistoriesColumns // columns contains all the column names of Table for convenient usage.
}

// UserPostsHistoriesColumns defines and stores column names for table forum_user_posts_histories.
type UserPostsHistoriesColumns struct {
	Id        string //
	UserId    string // 用户id
	Username  string // 用户名
	PostsId   string // 关联主题id
	CreatedAt string // 创建时间
	DeletedAt string // 删除时间
}

//  UserPostsHistoriesColumns holds the columns for table forum_user_posts_histories.
var userPostsHistoriesColumns = UserPostsHistoriesColumns{
	Id:        "id",
	UserId:    "user_id",
	Username:  "username",
	PostsId:   "posts_id",
	CreatedAt: "created_at",
	DeletedAt: "deleted_at",
}

// NewUserPostsHistoriesDao creates and returns a new DAO object for table data access.
func NewUserPostsHistoriesDao() *UserPostsHistoriesDao {
	return &UserPostsHistoriesDao{
		group:   "default",
		table:   "forum_user_posts_histories",
		columns: userPostsHistoriesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserPostsHistoriesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserPostsHistoriesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserPostsHistoriesDao) Columns() UserPostsHistoriesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserPostsHistoriesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserPostsHistoriesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserPostsHistoriesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
